Created Portfolio project
ksigei/Portfolio1 pull request #1
Opened 2022-02-09 09:59 UTC by ksigei

### Portfolio project

2022-02-09 20:34 UTC, BenMukebo requested changes
### Hi **@Kip Kiprono,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Cheers :clinking_glasses:  and Happy coding!!! :dancers:

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 20:34 UTC, BenMukebo commented on index.html
> +        </div>
- [ ] Please, wrap these `2 divs` inside a `header` tag, this should represent the header section, by this, the div containing the humburger should be replaced with a `nav` tag instead.

2022-02-09 20:34 UTC, BenMukebo commented on index.html
> +        </div> -->
- [ ] Please, don't leave unused code as commented in your codebase, removing them will make your code professional and clean, let's go and fix it 😄

2022-02-09 20:34 UTC, BenMukebo commented on style.css
> +  /* or 50px */
- [ ] Please, do the same for this line too 😄

2022-02-10 04:26 UTC, keroloussamy approved these changes
Hi @ksigei, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions

- [ ] Please remember to name your branch with a descriptive name instead of `milestone1`, e.g. 'created toolbar and headline' or 'added-toolbar-and-headline-sections'

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 04:49 UTC, merged