Created mobile version of the portfolio
ksigei/Portfolio1 pull request #2
Opened 2022-02-12 09:10 UTC by ksigei

**In this milestone, I was able to:**

- Understand how to parse a Figma design to create a UI.
- Use Flexbox to place elements on the page.
- Use CSS Grid to place elements on the page.
- Add two sections to my personal portfolio site.
      -Works section
      -About myself myself section

I also used correctly [GitHub Flow]:
I learned to write a descriptive README file.

2022-02-12 22:36 UTC, codepantherr requested changes
Hi @ksigei 👋 , 

You have done a great job so far. Well done 😎 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Things to highlight ⚡ 
- Descriptive README
- Meaningful commits and PR description

## Suggested changes ♻️ 
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-12 22:36 UTC, codepantha commented on index.html
> +  <section class="projects">
- [ ] Please use CSS Grid to layout the main container of `<section class="projects">` according to the project requirements. 👍

2022-02-12 22:36 UTC, codepantha commented on index.html
> +            <img class="project-img" src="images/Rectangle 21 (1).png" alt="image">
- [ ] Let's make this a background image and not an `<img />` tag. Decorations should always background images, not `img ` tags. This [resource](https://www.w3schools.com/cssref/pr_background-image.asp) should help if you need a pointer 🤓 
- [ ] Let's align the content of this container with CSS flexbox according to the requirements ✔️

2022-02-12 22:36 UTC, codepantha commented on index.html
> +  <section class="projects">
- [ ] You are missing a 'Projects' title for your projects section. please add a 'Projects' inside a heading tag as the title in this section.

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
- [ ] The list of project technologies (e.g., "JavaScript", "HTML" and "CSS") should be list items `<li>` tags not `<button>` inside an unordered list `ul` tag as this is the right way ✔️  to markup a list of things.

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +        <h1>About</h1>
- [ ] Please let's make this any other header `<hx>` tag apart from `<h1>`. You should only have one `<h1>` tag on your page and it should be around the top. Any other occurrence should be changed to between `<h2>` and `<h6>` tags 🙏

2022-02-12 22:36 UTC, codepantherr commented on style.css
> +.project-view-btn {
- [ ] Let's make sure to implement and follow the button styling: Active, Hover and Pressed
![image](https://user-images.githubusercontent.com/46839548/153730241-854c44ac-5d79-428c-b040-89ba81d10391.png)

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +                <li>CSS</li>
- [ ] Please ensure that the technology categories ("Languages", "Frameworks" and "Skills") are `<li>` items enclosed within a `<ul>`. This is the right way to markup a list of things. 👍

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +        </button>
- [ ] Let's make sure to implement and follow the button styling: Active, Hover and Pressed
![image](https://user-images.githubusercontent.com/46839548/153730468-bc0fa962-ea92-4855-b369-b1ba4b980587.png)

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +        <h1>About</h1>
- [ ] Let's ensure that the content of this About section is aligned using CSS flexbox 🗳️

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +           <img class="images" src="images/#.svg" alt="#">
- [ ] Please fix this image. It is currently not displaying.

2022-02-12 22:36 UTC, codepantherr commented on index.html
> +            <img class="images" src="images/Group_18.png" alt="#">
- [ ] Please fix this image. It is currently not displaying.

2022-02-12 22:38 UTC, ksigei commented
I'm pushing now, 5 minutes 🤦

On Sun, Feb 13, 2022, 1:36 AM Eze Promise ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ksigei <https://github.com/ksigei> 👋 ,
>
> You have done a great job so far. Well done 😎
> There are some issues that you still need to work on to prepare your
> project for the final evaluation but you are almost there!
> Things to highlight ⚡
>
>    - Descriptive README
>    - Meaningful commits and PR description
>
> Suggested changes ♻️
>
> *Check the comments under the review.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805205945>:
>
> >        </section>
>
>          <div class="header-img-bottom">
>
>              <img src="images/image_geometry_2.png" alt="image">
>
>          </div>
>
>      </header>
>
> +  <section class="projects">
>
>
>
>    - Please use CSS Grid to layout the main container of <section
>    class="projects"> according to the project requirements. 👍
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805206807>:
>
> >        </section>
>
>          <div class="header-img-bottom">
>
>              <img src="images/image_geometry_2.png" alt="image">
>
>          </div>
>
>      </header>
>
> +  <section class="projects">
>
> +    <div class="projects-wrapper">
>
> +        <div class="project-image">
>
> +            <img class="project-img" src="images/Rectangle 21 (1).png" alt="image">
>
>
>
>    - Let's make this a background image and not an <img /> tag.
>    Decorations should always background images, not img tags. This
>    resource <https://www.w3schools.com/cssref/pr_background-image.asp>
>    should help if you need a pointer 🤓
>    - Let's align the content of this container with CSS flexbox according
>    to the requirements ✔️
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805207416>:
>
> >        </section>
>
>          <div class="header-img-bottom">
>
>              <img src="images/image_geometry_2.png" alt="image">
>
>          </div>
>
>      </header>
>
> +  <section class="projects">
>
>
>
>    - You are missing a 'Projects' title for your projects section. please
>    add a 'Projects' inside a heading tag as the title in this section.
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209162>:
>
> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>
> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>
> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>
>
>
>    - The list of project technologies (e.g., "JavaScript", "HTML" and
>    "CSS") should be list items <li> tags not <button> inside an unordered
>    list ul tag as this is the right way ✔️ to markup a list of things.
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209681>:
>
> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>
> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>
> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>
> +
>
> +            <button type="submit" id="project-view">
>
> +                <span class="project-view-union">See this project</span>
>
> +
>
> +                <span><img id="union" src="images/Union.png" alt="union"></span>
>
> +            </button>
>
> +          </div>
>
> +        </div>
>
> +    </div>
>
> +  </section>
>
> +  <section class="about">
>
> +    <div class="about-me">
>
> +        <h1>About</h1>
>
>
>
>    - Please let's make this any other header <hx> tag apart from <h1>.
>    You should only have one <h1> tag on your page and it should be around
>    the top. Any other occurrence should be changed to between <h2> and
>    <h6> tags 🙏
>
> ------------------------------
>
> In style.css
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210364>:
>
> > +  height: 126px;
>
> +  font-family: Poppins, Arial, Helvetica, sans-serif;
>
> +  font-style: normal;
>
> +  font-weight: normal;
>
> +  font-size: 14px;
>
> +  line-height: 21px;
>
> +  color: #1a2236;
>
> +}
>
> +
>
> +#about-view {
>
> +  width: 288px;
>
> +  height: 50px;
>
> +  background: #1a2236;
>
> +}
>
> +
>
> +.project-view-btn {
>
>
>
>    - Let's make sure to implement and follow the button styling: Active,
>    Hover and Pressed
>    [image: image]
>    <https://user-images.githubusercontent.com/46839548/153730241-854c44ac-5d79-428c-b040-89ba81d10391.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210840>:
>
> > +    <section class="langs-section">
>
> +        <div class="langs">
>
> +           <div class="content-list">
>
> +            <h3>Languages</h3>
>
> +            <ul>
>
> +                <li>JavaScript (ES5/ES6)</li>
>
> +                <li>Ruby</li>
>
> +                <li>HTML</li>
>
> +                <li>CSS</li>
>
>
>
>    - Please ensure that the technology categories ("Languages",
>    "Frameworks" and "Skills") are <li> items enclosed within a <ul>. This
>    is the right way to markup a list of things. 👍
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211034>:
>
> > +        <button type="submit" id="about-view">
>
> +            <span class="project-view-btn">Get my CV</span>
>
> +
>
> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>
> +        </button>
>
>
>
>    - Let's make sure to implement and follow the button styling: Active,
>    Hover and Pressed
>    [image: image]
>    <https://user-images.githubusercontent.com/46839548/153730468-bc0fa962-ea92-4855-b369-b1ba4b980587.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211252>:
>
> > +  <section class="about">
>
> +    <div class="about-me">
>
> +        <h1>About</h1>
>
>
>
>    - Let's ensure that the content of this About section is aligned using
>    CSS flexbox 🗳️
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211427>:
>
> > +
>
> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>
> +        </button>
>
> +    </div>
>
> +    <section class="langs-section">
>
> +        <div class="langs">
>
> +           <div class="content-list">
>
> +            <h3>Languages</h3>
>
> +            <ul>
>
> +                <li>JavaScript (ES5/ES6)</li>
>
> +                <li>Ruby</li>
>
> +                <li>HTML</li>
>
> +                <li>CSS</li>
>
> +            </ul>
>
> +           </div>
>
> +           <img class="images" src="images/#.svg" alt="#">
>
>
>
>    - Please fix this image. It is currently not displaying.
>
> ------------------------------
>
> In index.html
> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211476>:
>
> > +           </div>
>
> +           <img class="images" src="images/#.svg" alt="#">
>
> +        </div>
>
> +        <div class="frameworks">
>
> +            <div class="content-list">
>
> +                <h3>Frameworks</h3>
>
> +            <ul>
>
> +                <li>Bootstrap</li>
>
> +                <li>Ruby on rails</li>
>
> +        [...]

2022-02-12 22:51 UTC, ksigei commented
Done now🤦🤦🤦🤦

On Sun, Feb 13, 2022, 1:38 AM Sigei Kiprono ***@***.***> wrote:

> I'm pushing now, 5 minutes 🤦
>
> On Sun, Feb 13, 2022, 1:36 AM Eze Promise ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @ksigei <https://github.com/ksigei> 👋 ,
>>
>> You have done a great job so far. Well done 😎
>> There are some issues that you still need to work on to prepare your
>> project for the final evaluation but you are almost there!
>> Things to highlight ⚡
>>
>>    - Descriptive README
>>    - Meaningful commits and PR description
>>
>> Suggested changes ♻️
>>
>> *Check the comments under the review.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805205945>:
>>
>> >        </section>
>>
>>          <div class="header-img-bottom">
>>
>>              <img src="images/image_geometry_2.png" alt="image">
>>
>>          </div>
>>
>>      </header>
>>
>> +  <section class="projects">
>>
>>
>>
>>    - Please use CSS Grid to layout the main container of <section
>>    class="projects"> according to the project requirements. 👍
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805206807>:
>>
>> >        </section>
>>
>>          <div class="header-img-bottom">
>>
>>              <img src="images/image_geometry_2.png" alt="image">
>>
>>          </div>
>>
>>      </header>
>>
>> +  <section class="projects">
>>
>> +    <div class="projects-wrapper">
>>
>> +        <div class="project-image">
>>
>> +            <img class="project-img" src="images/Rectangle 21 (1).png" alt="image">
>>
>>
>>
>>    - Let's make this a background image and not an <img /> tag.
>>    Decorations should always background images, not img tags. This
>>    resource <https://www.w3schools.com/cssref/pr_background-image.asp>
>>    should help if you need a pointer 🤓
>>    - Let's align the content of this container with CSS flexbox
>>    according to the requirements ✔️
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805207416>:
>>
>> >        </section>
>>
>>          <div class="header-img-bottom">
>>
>>              <img src="images/image_geometry_2.png" alt="image">
>>
>>          </div>
>>
>>      </header>
>>
>> +  <section class="projects">
>>
>>
>>
>>    - You are missing a 'Projects' title for your projects section.
>>    please add a 'Projects' inside a heading tag as the title in this section.
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209162>:
>>
>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>
>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>
>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>
>>
>>
>>    - The list of project technologies (e.g., "JavaScript", "HTML" and
>>    "CSS") should be list items <li> tags not <button> inside an
>>    unordered list ul tag as this is the right way ✔️ to markup a list of
>>    things.
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209681>:
>>
>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>
>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>
>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>
>> +
>>
>> +            <button type="submit" id="project-view">
>>
>> +                <span class="project-view-union">See this project</span>
>>
>> +
>>
>> +                <span><img id="union" src="images/Union.png" alt="union"></span>
>>
>> +            </button>
>>
>> +          </div>
>>
>> +        </div>
>>
>> +    </div>
>>
>> +  </section>
>>
>> +  <section class="about">
>>
>> +    <div class="about-me">
>>
>> +        <h1>About</h1>
>>
>>
>>
>>    - Please let's make this any other header <hx> tag apart from <h1>.
>>    You should only have one <h1> tag on your page and it should be
>>    around the top. Any other occurrence should be changed to between <h2>
>>    and <h6> tags 🙏
>>
>> ------------------------------
>>
>> In style.css
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210364>:
>>
>> > +  height: 126px;
>>
>> +  font-family: Poppins, Arial, Helvetica, sans-serif;
>>
>> +  font-style: normal;
>>
>> +  font-weight: normal;
>>
>> +  font-size: 14px;
>>
>> +  line-height: 21px;
>>
>> +  color: #1a2236;
>>
>> +}
>>
>> +
>>
>> +#about-view {
>>
>> +  width: 288px;
>>
>> +  height: 50px;
>>
>> +  background: #1a2236;
>>
>> +}
>>
>> +
>>
>> +.project-view-btn {
>>
>>
>>
>>    - Let's make sure to implement and follow the button styling: Active,
>>    Hover and Pressed
>>    [image: image]
>>    <https://user-images.githubusercontent.com/46839548/153730241-854c44ac-5d79-428c-b040-89ba81d10391.png>
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210840>:
>>
>> > +    <section class="langs-section">
>>
>> +        <div class="langs">
>>
>> +           <div class="content-list">
>>
>> +            <h3>Languages</h3>
>>
>> +            <ul>
>>
>> +                <li>JavaScript (ES5/ES6)</li>
>>
>> +                <li>Ruby</li>
>>
>> +                <li>HTML</li>
>>
>> +                <li>CSS</li>
>>
>>
>>
>>    - Please ensure that the technology categories ("Languages",
>>    "Frameworks" and "Skills") are <li> items enclosed within a <ul>.
>>    This is the right way to markup a list of things. 👍
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211034>:
>>
>> > +        <button type="submit" id="about-view">
>>
>> +            <span class="project-view-btn">Get my CV</span>
>>
>> +
>>
>> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>>
>> +        </button>
>>
>>
>>
>>    - Let's make sure to implement and follow the button styling: Active,
>>    Hover and Pressed
>>    [image: image]
>>    <https://user-images.githubusercontent.com/46839548/153730468-bc0fa962-ea92-4855-b369-b1ba4b980587.png>
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211252>:
>>
>> > +  <section class="about">
>>
>> +    <div class="about-me">
>>
>> +        <h1>About</h1>
>>
>>
>>
>>    - Let's ensure that the content of this About section is aligned
>>    using CSS flexbox 🗳️
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211427>:
>>
>> > +
>>
>> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>>
>> +        </button>
>>
>> +    </div>
>>
>> +    <section class="langs-section">
>>
>> +        <div class="langs">
>>
>> +           <div class="content-list">
>>
>> +            <h3>Languages</h3>
>>
>> +            <ul>
>>
>> +                <li>JavaScript (ES5/ES6)</li>
>>
>> +                <li>Ruby</li>
>>
>> +                <li>HTML</li>
>>
>> +                <li>CSS</li>
>>
>> +            </ul>
>>
>> +           </div>
>>
>> +           <img class="images" src="images/#.svg" alt="#">
>>
>>
>>
>>    - Please fix this image. It is currently not displaying.
>>
>> ------------------------------
>>
>> In index.html
>> <https:/ [...]

2022-02-12 23:00 UTC, ksigei commented
👋

On Sun, Feb 13, 2022, 1:50 AM Sigei Kiprono ***@***.***> wrote:

> Done now🤦🤦🤦🤦
>
> On Sun, Feb 13, 2022, 1:38 AM Sigei Kiprono ***@***.***>
> wrote:
>
>> I'm pushing now, 5 minutes 🤦
>>
>> On Sun, Feb 13, 2022, 1:36 AM Eze Promise ***@***.***>
>> wrote:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> Hi @ksigei <https://github.com/ksigei> 👋 ,
>>>
>>> You have done a great job so far. Well done 😎
>>> There are some issues that you still need to work on to prepare your
>>> project for the final evaluation but you are almost there!
>>> Things to highlight ⚡
>>>
>>>    - Descriptive README
>>>    - Meaningful commits and PR description
>>>
>>> Suggested changes ♻️
>>>
>>> *Check the comments under the review.*
>>>
>>> Cheers and Happy coding!👏👏👏
>>>
>>> Feel free to leave any questions or comments in the PR thread if
>>> something is not 100% clear.
>>>
>>> *Please, do not open a new Pull Request for re-reviews. You should use
>>> the same Pull Request submitted for the first review, either valid or
>>> invalid unless it is requested otherwise.*
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805205945>:
>>>
>>> >        </section>
>>>
>>>          <div class="header-img-bottom">
>>>
>>>              <img src="images/image_geometry_2.png" alt="image">
>>>
>>>          </div>
>>>
>>>      </header>
>>>
>>> +  <section class="projects">
>>>
>>>
>>>
>>>    - Please use CSS Grid to layout the main container of <section
>>>    class="projects"> according to the project requirements. 👍
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805206807>:
>>>
>>> >        </section>
>>>
>>>          <div class="header-img-bottom">
>>>
>>>              <img src="images/image_geometry_2.png" alt="image">
>>>
>>>          </div>
>>>
>>>      </header>
>>>
>>> +  <section class="projects">
>>>
>>> +    <div class="projects-wrapper">
>>>
>>> +        <div class="project-image">
>>>
>>> +            <img class="project-img" src="images/Rectangle 21 (1).png" alt="image">
>>>
>>>
>>>
>>>    - Let's make this a background image and not an <img /> tag.
>>>    Decorations should always background images, not img tags. This
>>>    resource <https://www.w3schools.com/cssref/pr_background-image.asp>
>>>    should help if you need a pointer 🤓
>>>    - Let's align the content of this container with CSS flexbox
>>>    according to the requirements ✔️
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805207416>:
>>>
>>> >        </section>
>>>
>>>          <div class="header-img-bottom">
>>>
>>>              <img src="images/image_geometry_2.png" alt="image">
>>>
>>>          </div>
>>>
>>>      </header>
>>>
>>> +  <section class="projects">
>>>
>>>
>>>
>>>    - You are missing a 'Projects' title for your projects section.
>>>    please add a 'Projects' inside a heading tag as the title in this section.
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209162>:
>>>
>>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>>
>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>>
>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>>
>>>
>>>
>>>    - The list of project technologies (e.g., "JavaScript", "HTML" and
>>>    "CSS") should be list items <li> tags not <button> inside an
>>>    unordered list ul tag as this is the right way ✔️ to markup a list
>>>    of things.
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209681>:
>>>
>>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>>
>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>>
>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>>
>>> +
>>>
>>> +            <button type="submit" id="project-view">
>>>
>>> +                <span class="project-view-union">See this project</span>
>>>
>>> +
>>>
>>> +                <span><img id="union" src="images/Union.png" alt="union"></span>
>>>
>>> +            </button>
>>>
>>> +          </div>
>>>
>>> +        </div>
>>>
>>> +    </div>
>>>
>>> +  </section>
>>>
>>> +  <section class="about">
>>>
>>> +    <div class="about-me">
>>>
>>> +        <h1>About</h1>
>>>
>>>
>>>
>>>    - Please let's make this any other header <hx> tag apart from <h1>.
>>>    You should only have one <h1> tag on your page and it should be
>>>    around the top. Any other occurrence should be changed to between
>>>    <h2> and <h6> tags 🙏
>>>
>>> ------------------------------
>>>
>>> In style.css
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210364>:
>>>
>>> > +  height: 126px;
>>>
>>> +  font-family: Poppins, Arial, Helvetica, sans-serif;
>>>
>>> +  font-style: normal;
>>>
>>> +  font-weight: normal;
>>>
>>> +  font-size: 14px;
>>>
>>> +  line-height: 21px;
>>>
>>> +  color: #1a2236;
>>>
>>> +}
>>>
>>> +
>>>
>>> +#about-view {
>>>
>>> +  width: 288px;
>>>
>>> +  height: 50px;
>>>
>>> +  background: #1a2236;
>>>
>>> +}
>>>
>>> +
>>>
>>> +.project-view-btn {
>>>
>>>
>>>
>>>    - Let's make sure to implement and follow the button styling:
>>>    Active, Hover and Pressed
>>>    [image: image]
>>>    <https://user-images.githubusercontent.com/46839548/153730241-854c44ac-5d79-428c-b040-89ba81d10391.png>
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210840>:
>>>
>>> > +    <section class="langs-section">
>>>
>>> +        <div class="langs">
>>>
>>> +           <div class="content-list">
>>>
>>> +            <h3>Languages</h3>
>>>
>>> +            <ul>
>>>
>>> +                <li>JavaScript (ES5/ES6)</li>
>>>
>>> +                <li>Ruby</li>
>>>
>>> +                <li>HTML</li>
>>>
>>> +                <li>CSS</li>
>>>
>>>
>>>
>>>    - Please ensure that the technology categories ("Languages",
>>>    "Frameworks" and "Skills") are <li> items enclosed within a <ul>.
>>>    This is the right way to markup a list of things. 👍
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211034>:
>>>
>>> > +        <button type="submit" id="about-view">
>>>
>>> +            <span class="project-view-btn">Get my CV</span>
>>>
>>> +
>>>
>>> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>>>
>>> +        </button>
>>>
>>>
>>>
>>>    - Let's make sure to implement and follow the button styling:
>>>    Active, Hover and Pressed
>>>    [image: image]
>>>    <https://user-images.githubusercontent.com/46839548/153730468-bc0fa962-ea92-4855-b369-b1ba4b980587.png>
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211252>:
>>>
>>> > +  <section class="about">
>>>
>>> +    <div class="about-me">
>>>
>>> +        <h1>About</h1>
>>>
>>>
>>>
>>>    - Let's ensure that the content of this About section is aligned
>>>    using CSS flexbox 🗳️
>>>
>>> ------------------------------
>>>
>>> In index.html
>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211427>:
>>>
>>> > +
>>>
>>> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>>>
>>> +        </button>
>>>
>>> +    </div>
>>>
>>> +    <section class="langs-section">
>>>
>>> +        <div class="langs">
>>>
>>> +           <div class="content-list">
>>>
>>> +            <h3>Languages</h3>
>>>
>>> +            <ul>
>>>
>>> +                <li>JavaScript (ES [...]

2022-02-12 23:12 UTC, ksigei commented
Oops 😬

On Sun, Feb 13, 2022, 2:00 AM Sigei Kiprono ***@***.***> wrote:

> 👋
>
> On Sun, Feb 13, 2022, 1:50 AM Sigei Kiprono ***@***.***>
> wrote:
>
>> Done now🤦🤦🤦🤦
>>
>> On Sun, Feb 13, 2022, 1:38 AM Sigei Kiprono ***@***.***>
>> wrote:
>>
>>> I'm pushing now, 5 minutes 🤦
>>>
>>> On Sun, Feb 13, 2022, 1:36 AM Eze Promise ***@***.***>
>>> wrote:
>>>
>>>> ***@***.**** requested changes on this pull request.
>>>>
>>>> Hi @ksigei <https://github.com/ksigei> 👋 ,
>>>>
>>>> You have done a great job so far. Well done 😎
>>>> There are some issues that you still need to work on to prepare your
>>>> project for the final evaluation but you are almost there!
>>>> Things to highlight ⚡
>>>>
>>>>    - Descriptive README
>>>>    - Meaningful commits and PR description
>>>>
>>>> Suggested changes ♻️
>>>>
>>>> *Check the comments under the review.*
>>>>
>>>> Cheers and Happy coding!👏👏👏
>>>>
>>>> Feel free to leave any questions or comments in the PR thread if
>>>> something is not 100% clear.
>>>>
>>>> *Please, do not open a new Pull Request for re-reviews. You should use
>>>> the same Pull Request submitted for the first review, either valid or
>>>> invalid unless it is requested otherwise.*
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805205945>:
>>>>
>>>> >        </section>
>>>>
>>>>          <div class="header-img-bottom">
>>>>
>>>>              <img src="images/image_geometry_2.png" alt="image">
>>>>
>>>>          </div>
>>>>
>>>>      </header>
>>>>
>>>> +  <section class="projects">
>>>>
>>>>
>>>>
>>>>    - Please use CSS Grid to layout the main container of <section
>>>>    class="projects"> according to the project requirements. 👍
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805206807>:
>>>>
>>>> >        </section>
>>>>
>>>>          <div class="header-img-bottom">
>>>>
>>>>              <img src="images/image_geometry_2.png" alt="image">
>>>>
>>>>          </div>
>>>>
>>>>      </header>
>>>>
>>>> +  <section class="projects">
>>>>
>>>> +    <div class="projects-wrapper">
>>>>
>>>> +        <div class="project-image">
>>>>
>>>> +            <img class="project-img" src="images/Rectangle 21 (1).png" alt="image">
>>>>
>>>>
>>>>
>>>>    - Let's make this a background image and not an <img /> tag.
>>>>    Decorations should always background images, not img tags. This
>>>>    resource <https://www.w3schools.com/cssref/pr_background-image.asp>
>>>>    should help if you need a pointer 🤓
>>>>    - Let's align the content of this container with CSS flexbox
>>>>    according to the requirements ✔️
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805207416>:
>>>>
>>>> >        </section>
>>>>
>>>>          <div class="header-img-bottom">
>>>>
>>>>              <img src="images/image_geometry_2.png" alt="image">
>>>>
>>>>          </div>
>>>>
>>>>      </header>
>>>>
>>>> +  <section class="projects">
>>>>
>>>>
>>>>
>>>>    - You are missing a 'Projects' title for your projects section.
>>>>    please add a 'Projects' inside a heading tag as the title in this section.
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209162>:
>>>>
>>>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>>>
>>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>>>
>>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>>>
>>>>
>>>>
>>>>    - The list of project technologies (e.g., "JavaScript", "HTML" and
>>>>    "CSS") should be list items <li> tags not <button> inside an
>>>>    unordered list ul tag as this is the right way ✔️ to markup a list
>>>>    of things.
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805209681>:
>>>>
>>>> > +            <button type="submit" class="project-btn-1"><span class="btn-p">HTML/CSS</span></button>
>>>>
>>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">Ruby on Rails</span></button>
>>>>
>>>> +            <button type="submit" class="project-btn-1"><span class="btn-p">JavaScript</span></button>
>>>>
>>>> +
>>>>
>>>> +            <button type="submit" id="project-view">
>>>>
>>>> +                <span class="project-view-union">See this project</span>
>>>>
>>>> +
>>>>
>>>> +                <span><img id="union" src="images/Union.png" alt="union"></span>
>>>>
>>>> +            </button>
>>>>
>>>> +          </div>
>>>>
>>>> +        </div>
>>>>
>>>> +    </div>
>>>>
>>>> +  </section>
>>>>
>>>> +  <section class="about">
>>>>
>>>> +    <div class="about-me">
>>>>
>>>> +        <h1>About</h1>
>>>>
>>>>
>>>>
>>>>    - Please let's make this any other header <hx> tag apart from <h1>.
>>>>    You should only have one <h1> tag on your page and it should be
>>>>    around the top. Any other occurrence should be changed to between
>>>>    <h2> and <h6> tags 🙏
>>>>
>>>> ------------------------------
>>>>
>>>> In style.css
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210364>:
>>>>
>>>> > +  height: 126px;
>>>>
>>>> +  font-family: Poppins, Arial, Helvetica, sans-serif;
>>>>
>>>> +  font-style: normal;
>>>>
>>>> +  font-weight: normal;
>>>>
>>>> +  font-size: 14px;
>>>>
>>>> +  line-height: 21px;
>>>>
>>>> +  color: #1a2236;
>>>>
>>>> +}
>>>>
>>>> +
>>>>
>>>> +#about-view {
>>>>
>>>> +  width: 288px;
>>>>
>>>> +  height: 50px;
>>>>
>>>> +  background: #1a2236;
>>>>
>>>> +}
>>>>
>>>> +
>>>>
>>>> +.project-view-btn {
>>>>
>>>>
>>>>
>>>>    - Let's make sure to implement and follow the button styling:
>>>>    Active, Hover and Pressed
>>>>    [image: image]
>>>>    <https://user-images.githubusercontent.com/46839548/153730241-854c44ac-5d79-428c-b040-89ba81d10391.png>
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805210840>:
>>>>
>>>> > +    <section class="langs-section">
>>>>
>>>> +        <div class="langs">
>>>>
>>>> +           <div class="content-list">
>>>>
>>>> +            <h3>Languages</h3>
>>>>
>>>> +            <ul>
>>>>
>>>> +                <li>JavaScript (ES5/ES6)</li>
>>>>
>>>> +                <li>Ruby</li>
>>>>
>>>> +                <li>HTML</li>
>>>>
>>>> +                <li>CSS</li>
>>>>
>>>>
>>>>
>>>>    - Please ensure that the technology categories ("Languages",
>>>>    "Frameworks" and "Skills") are <li> items enclosed within a <ul>.
>>>>    This is the right way to markup a list of things. 👍
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211034>:
>>>>
>>>> > +        <button type="submit" id="about-view">
>>>>
>>>> +            <span class="project-view-btn">Get my CV</span>
>>>>
>>>> +
>>>>
>>>> +            <span><img id="cv-btn" src="images/ic_download.png" alt="union"></span>
>>>>
>>>> +        </button>
>>>>
>>>>
>>>>
>>>>    - Let's make sure to implement and follow the button styling:
>>>>    Active, Hover and Pressed
>>>>    [image: image]
>>>>    <https://user-images.githubusercontent.com/46839548/153730468-bc0fa962-ea92-4855-b369-b1ba4b980587.png>
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211252>:
>>>>
>>>> > +  <section class="about">
>>>>
>>>> +    <div class="about-me">
>>>>
>>>> +        <h1>About</h1>
>>>>
>>>>
>>>>
>>>>    - Let's ensure that the content of this About section is aligned
>>>>    using CSS flexbox 🗳️
>>>>
>>>> ------------------------------
>>>>
>>>> In index.html
>>>> <https://github.com/ksigei/Portfolio/pull/2#discussion_r805211427>:
>>>>
>>>> > +
>>>>
>>> [...]

2022-02-12 23:21 UTC, Hope1226 requested changes
Hi @ksigei , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :stop_sign: 
### Why this happened :question: :question: 

You have submitted a project while modifying the [linters.yml](https://github.com/ksigei/Portfolio/blob/milestone2/.github/workflows/linters.yml) as well as without addressing the required changes by the previous code reviewer:

- [ ] Please get back the block of code for both `webhint` and `stylelint` into your [linters.yml](https://github.com/ksigei/Portfolio/blob/milestone2/.github/workflows/linters.yml)and make sure all checks are passed
- [ ] Please kindly address all the above-mentioned comments by the previous CR before requesting for re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-13 04:04 UTC, ksigei commented
You people took time to reach out to me, the dashboard has been closed
🔒🤦💔💔💔

On Sun, Feb 13, 2022, 2:22 AM Umidjon Ustabaev ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ksigei <https://github.com/ksigei> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request 🛑 Why this happened ❓ ❓
>
> You have submitted a project while modifying the linters.yml
> <https://github.com/ksigei/Portfolio/blob/milestone2/.github/workflows/linters.yml>
> as well as without addressing the required changes by the previous code
> reviewer:
>
>    - Please get back the block of code for both webhint and stylelint
>    into your linters.yml
>    <https://github.com/ksigei/Portfolio/blob/milestone2/.github/workflows/linters.yml>and
>    make sure all checks are passed
>    - Please kindly address all the above-mentioned comments by the
>    previous CR before requesting for re-review.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ksigei/Portfolio/pull/2#pullrequestreview-880898623>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWDI7XF7ZJPGD7G5JXYCPCLU23TRXANCNFSM5OGOYCTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-13 04:17 UTC, ksigei commented
No comment

2022-02-13 04:17 UTC, ksigei commented
💔

2022-02-13 04:17 UTC, closed without merging